GET http://localhost:3000/api/v1/book
Content-Type: application/json

###
GET http://localhost:3000/api/v1/book/2
Content-Type: application/json


###
POST http://localhost:3000/api/v1/book
Content-Type: application/json

###
POST http://localhost:3000/api/v1/book
Content-Type: application/json

{
    "title": "Go fiber v2",
    "author": "Sutin",
    "rating": 30
}

###
DELETE  http://localhost:3000/api/v1/book/1
Content-Type: application/json



